#! /usr/bin/bash

find Musica -name "flycheck*.py" -exec rm {} \;
find Musica -name "parsetab.py" -exec rm {} \;

api=doc/sphinx/source/api

echo
echo Generate RST API files
generate-rst-api Musica

echo
echo Run Sphinx
pushd doc/sphinx/
./make-html #--clean
popd
