#! /bin/bash

# source ~/.bashrc
# py36

source /opt/python-virtual-env/py36/bin/activate

python3 setup.py check --verbose --metadata --restructuredtext --strict && \
  python3 setup.py register sdist upload

# bdist
# bdist_wheel
