#! /bin/bash

# source ~/.bashrc
# py36

source /opt/python-virtual-env/py36/bin/activate

# bdist

python3 setup.py check --verbose --metadata --restructuredtext --strict && \
  python3 setup.py register sdist bdist_wheel upload
